# dev

version: "3"

services:
  app:
    image: sh7e-app:dev
    build: 
      target: dev
      # tags: ["sh7e-app:dev"]   # image要素があるので不要 (imageで設定している名前で書き出される)。
    environment:
      DEBUG_MODE: 1
      DISABLE_API: 1
    volumes:
      - ./services/app/static/:/app/static/:ro
      - ./services/app/templates/:/app/templates/:ro
      - ./services/app/mymodule.py:/app/mymodule.py:ro
      - ./services/app/run.py:/app/run.py:ro
      - ./services/app/set_pron_caches.py:/app/set_pron_caches.py:ro
      - ./services/app/uwsgi.ini:/app/uwsgi.ini:ro
  
  db:
    image: sh7e-db:dev
    build:
      target: dev
    volumes:
      - ./services/db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
      - ./services/db/mysql-files/:/var/lib/mysql-files/
  
  web:
    image: sh7e-web:dev
    build:
      target: dev
    # # stg, prodではfork爆弾等への対策としてプロセス数を制限すべく以下を追加。
    # deploy:
    #   resources:
    #     limits:
    #       pids: 20
    volumes:
      - ./services/web/nginx.conf:/etc/nginx/nginx.conf
      - ./services/web/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./services/web/ssl_certs_dummy/:/etc/ssl/certs/nginx/
      - ./services/web/geoip_db_dummy/:/usr/share/GeoIP/
  
  # # さまざまな用途にdebianを。
  # debian:
  #   image: debian:latest
  #   profiles:
  #     - "extra"
  #   volumes:
  #     - geoip_db:/usr/share/GeoIP
  # # 起動方法： $ docker compose -f compose.yaml -f compose.dev.yaml run debian bash
  # # たとえば、nginx.confのgeoip2ロケーションにおけるデータのパスを調べたければ、
  # # 次のようにmmdblookup toolを利用する。https://github.com/leev/ngx_http_geoip2_module#geoip
  # # $ apt update && apt install -y mmdb-bin
  # # $ mmdblookup --file /usr/share/GeoIP/GeoLite2-City.mmdb --ip 8.8.8.8

  grafana:
    image: sh7e-grafana:dev
    build:
      target: dev
    volumes:
      - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
      # https://grafana.com/docs/grafana/latest/administration/provisioning/
      - ./services/grafana/provisioning/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./services/grafana/provisioning/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./services/grafana/provisioning/dashboard1.json:/var/lib/grafana/dashboards/dashboard1.json
      - ./services/grafana/provisioning/alerting.yaml:/etc/grafana/provisioning/alerting/alerting.yaml

  loki:
    image: sh7e-loki:dev
    build:
      target: dev
    volumes:
      - ./services/loki/config.yaml:/etc/loki/myconfig.yaml
    # networks:
    #   - fluentd_loki

  promtail:
    image: sh7e-promtail:dev
    build:
      target: dev
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 9080:9080     # 送られていることを確認するために
    volumes:
      - ./services/promtail/config.yaml:/etc/promtail/myconfig.yaml

  # fluentd:
  #   # image: fluent/fluentd:edge
  #   build: 
  #     context: ./services/fluentd/
  #     dockerfile: ./Dockerfile.dev
  #   environment:
  #     FLUENT_CONF: /services/fluentd/etc/fluent.conf
  #   volumes:
  #     - ./services/fluentd/fluent.conf:/fluentd/etc/fluent.conf
  #     - ./services/fluentd/plugin:/etc/fluent/plugin
  #     - nginx_logs:/var/log/nginx/
  #   networks:
  #     - fluentd_loki

# networks:
# #   fluentd_loki:
# #     driver: bridge
#   grafana_web:
#     driver: bridge