# prod

services:
  app:
    image: sh7e-app:prod
    build: 
      target: prod
    restart: always

  cache:
    user: redis
    restart: always

  db:
    image: sh7e-db:prod
    build: 
      target: prod
    restart: always

  web:
    image: sh7e-web:prod
    build: 
      target: prod
    restart: always
    deploy:
      resources:
        limits:
          pids: 20
    volumes:
      - ssl_certs:/etc/letsencrypt/
      - dist:/usr/share/nginx/html/ssl-proof/

  cert:
    image: certbot/certbot:v2.6.0
    restart: "no"
    profiles:
      - "extra"
    volumes:
      - ssl_certs:/etc/letsencrypt/
      - dist:/dist/
    command: --version

  geoip:
    image: ghcr.io/maxmind/geoipupdate:v6.0
    restart: "no"
    profiles:
      - "extra"
    environment:
      GEOIPUPDATE_EDITION_IDS: GeoLite2-City
    volumes:
      - geoip_db:/usr/share/GeoIP/

  grafana:
    image: sh7e-grafana:prod
    build:
      target: prod
    restart: always

  loki:
    image: sh7e-loki:prod
    build:
      target: prod
    restart: always
    volumes:
      - loki_data:/loki/

  promtail:
    image: sh7e-promtail:prod
    build:
      target: prod
    restart: always

volumes:
  loki_data:
    external: true
    name: sh7e_loki_data_1
  ssl_certs:
    external: true
    name: sh7e_ssl_certs_1
  dist: