# stg

services:
  app:
    image: sh7e-app:stg
    build: 
      target: stg
    environment:
      DISABLE_API: 1
    restart: always

  cache:
    user: redis
    restart: always

  db:
    image: sh7e-db:stg
    build: 
      target: stg
    restart: always

  web:
    image: sh7e-web:stg
    build: 
      target: stg
    restart: always
    deploy:
      resources:
        limits:
          pids: 20
    volumes:
      - ./services/web/ssl_certs_dummy/:/etc/ssl/certs/nginx/
      - ./services/web/geoip_db_dummy/:/usr/share/GeoIP/

  grafana:
    image: sh7e-grafana:stg
    build:
      target: stg
    restart: always

  loki:
    image: sh7e-loki:stg
    build:
      target: stg
    restart: always
    volumes:
      - loki_data:/loki/

  promtail:
    image: sh7e-promtail:stg
    build:
      target: stg
    restart: always

volumes:
  loki_data:
    external: true
    name: sh7e_loki_data_1