{
 "title": "Dashboard 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Access Ranking",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"web_access\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Status Code Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"web_access\"} |= ``"
    }
   ]
  },
  {
   "title": "IP Address World Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"web_access\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Time Line",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"web_access\"} | line_format `{{ __timestamp__ | unixEpoch | add 32400 | date \"15:04:05\" }} {{.request_method}} {{.request_uri}} {{.request_protocol}} {{.status}}`"
    }
   ]
  },
  {
   "title": "Slowest Page URI",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{job=\"web_access\"} |= ``"
    }
   ]
  }
 ]
}